### ISSUE TITLE
Popraviti README.md datoteku

### ISSUE THREAD

**Issue by nikovrdoljak** [unizd-sit-web/p15-zavrsni-projekt-isevo#1]
README.md datoteku bi trebalo popraviti. Redom slijedeće stvari:
* Ispraviti pravopisne greške
* Ne koristiti markdown oznake za zaglavlja tamo gdje ne treba. Dovoljan je jedan (H1 #) za naslov projekta i jedan (H2 ##) za podnaslov "Pokretanje".
* Na mjestima gdje nabrajaš staviti _markdown_ oznaku za liste (* ili 1., 2., 3...)
* Za pomoć s _markdown-om_ pogledaj npr. [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
* Malo bolje pojasniti/dopuniti postupak za pokretanje aplikacije

**Comment by isevo** [comment]
Obavljeno :)
