### ISSUE TITLE
Maknuti sadržaje od preuzete teme

### ISSUE THREAD

**Issue by sbuljat** [unizd-sit-web/p15-zavrsni-projekt-isevo#4]
Kad se koristi tema za izradu web aplikacije onda je potrebno maknuti sve sadržaje koji se ne tiču direktno teme web aplikacije. U ovom slučaju u footer-u svake stranice postoji sekcija "Our services" koja sadrži "Illustration",.. to treba maknuti obzirom da se ovdje radi o Pub Quiz aplikaciji.

**Comment by isevo** [comment]
Makla sam.
